### ISSUE TITLE
ApplyProvisioningTemplate fails with structural navigation on a modern site

### ISSUE THREAD

**Issue by biste5** [SharePoint/PnP-Sites-Core#1106]
#### Category
[ X ] Bug
[ ] Enhancement

#### Environment
[ X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I have a modern site just created, for which I extracted its provisioning template using PnP-PowerShell.
I want to reuse this template to apply to other modern sites

#### Observed Behavior
The extracted template contains the following XML portion

```xml
...
        <pnp:CurrentNavigation NavigationType="StructuralLocal">
          <pnp:StructuralNavigation RemoveExistingNodes="false">
            <pnp:NavigationNode Title="Home" Url="{site}" />
            <pnp:NavigationNode Title="Documents" Url="{site}/Shared Documents/Forms/AllItems.aspx" />
            <pnp:NavigationNode Title="Notebook" Url="{site}/_layouts/15/groupstatus.aspx?Target=NOTEBOOK" IsExternal="true" />
            <pnp:NavigationNode Title="Pages" Url="{site}/SitePages/Forms/ByAuthor.aspx" />
            <pnp:NavigationNode Title="Recent" Url="" IsExternal="true" />
            <pnp:NavigationNode Title="MyList" Url="{site}/Lists/MyList/AllItems.aspx" />
            <pnp:NavigationNode Title="Site contents" Url="{site}/_layouts/15/viewlsts.aspx" IsExternal="true" />
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>
...
```
(I added a simple custom list called _MyList_ to this site)

It generates an exception from [ObjectNavigation.cs#L156](https://github.com/SharePoint/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs#L156)

because that should be wrapped in a 
```c#
if (!web.IsNoScriptSite()){

}
```
in my modest opinion

#### Steps to Reproduce
- Create a new modern site (from UI)
- Add a new custom list named _MyList_ to the site (still using UI)
- Run `Get-PnPProvisioningTemplate` to get the template definition of that site
- Run `Apply-PnPProvisioningTemplate` against the same site

It will generate an exception

> Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Access denied. You do not have permission to perform this action or access this resource.

**Comment by jansenbe** [comment]
Hi @biste5, I've seen this as well in our test automation but not always. Can you always simulate? If so can you send me stacktrace and ideally a correlation ID and tenant name.

**Comment by biste5** [comment]
Hi Bert,

I think it isn't only in one place, and mostly are 'Access denied' generated while targeting **modern sites**. This is a very easy to reproduce one.
I saw some recent code changes from you to support them, wrapping needed code into that code block I indicate, as modern sites don't support property bag items. --> https://github.com/SharePoint/PnP-Sites-Core/commit/a34d26b4eb773bc4e5020e8aa059501c82918019#diff-ff0df558256a051dff5b7c6b727b4d38

This case is easy reproducible with a modern site, and that piece of XML I provided.
Anyway here the information you requested

Tenant name: mod144391
correlation ID: d26edc9d-e08f-3000-a313-942e5ca041dc
Stack Trace:
`   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 90
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\ClientContextExtensions.cs:line 45
   at Microsoft.SharePoint.Client.WebExtensions.SetPropertyBagValueInternal(Web web, String key, Object value) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\WebExtensions.cs:line 765
   at Microsoft.SharePoint.Client.WebExtensions.SetPropertyBagValue(Web web, String key, String value) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\WebExtensions.cs:line 724
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectNavigation.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\ObjectNavigation.cs:line 156
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 248
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in X:\GH\PnP-Sites-Core\Core\OfficeDevPnP.Core\Extensions\WebExtensions.cs:line 1174
   at PnPTemplatesConsole.Program.Main(String[] args) in C:\Users\massimo\Documents\Visual Studio 2015\Projects\PnPTemplatesConsole\PnPTemplatesConsole\Program.cs:line 34`

Hope this helps

**Comment by jansenbe** [comment]
Yes, seemed that we did not have automation testing for navigation with noscript...have investigated and this indeed does repro. I've changed the navigation handler to skip provisioning navigation objects in case of a noscript site. This will be in the March release we're getting out today :-) Will close this issue now, but feel free to re-open if the problem is not solved with the March release.

**Comment by biste5** [comment]
I think lots of tests are missing, especially specifics for modern sites :)

That seems fixed now (or at least not throwing exception anymore).
I still see issue applying simple templates to modern sites. I'll report them separately as I can reproduce them consistently

Cheers
