### ISSUE TITLE
Provisioning template generator does not include templates associated with content type

### ISSUE THREAD

**Issue by LenCardinal** [SharePoint/PnP-Sites-Core#378]
The template generator does not include references to document templates of a source content type.  In the example below, the content type had a template "PowerPointTemplate.pptx" associated with it.

```
    <pnp:ContentType ID="0x0101004436D1700185A94FA98E9B028EE05CAF" Name="PowerPoint presentation" Description="" Group="Custom Content Types" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
      <pnp:FieldRefs>
        <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
        <pnp:FieldRef ID="5f47e085-2150-41dc-b661-442f3027f552" Name="SelectFilename" />
        <pnp:FieldRef ID="8553196d-ec8d-4564-9861-3dbe931050c8" Name="FileLeafRef" Required="true" />
        <pnp:FieldRef ID="8c06beca-0777-48f7-91c7-6da68bc07b69" Name="Created" Hidden="true" />
        <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" />
        <pnp:FieldRef ID="28cf69c5-fa48-462a-b5cd-27b6f9d2bd5f" Name="Modified" Hidden="true" />
        <pnp:FieldRef ID="822c78e3-1ea9-4943-b449-57863ad33ca9" Name="Modified_x0020_By" />
        <pnp:FieldRef ID="4dd7e525-8d6b-4cb4-9d3e-44ee25f973eb" Name="Created_x0020_By" />
      </pnp:FieldRefs>
    </pnp:ContentType>
```

**Comment by jansenbe** [comment]
Hi Len,

In my testing I'm not seeing this behavior: the defined template is returned using the DocumentTemplate element. Sample XML that I used to create (and which is also returned) is shown below. 

Note: that we're not downloading the file if the user uploaded a file...in this case we just return <DocumentTemplate TargetName="_cts/CT_1/CT1Document.docx" />

```XML
    <pnp:ContentType ID="0x0101005D4F34E4BE7F4B6892AEBE088EDD215E" Name="CT_1" Description="CT 1" Group="PnP Demo">
      <pnp:FieldRefs>
        <pnp:FieldRef ID="{92BC6A41-D501-4FE2-938E-17FBF574A7CB}" />
      </pnp:FieldRefs>
      <pnp:DocumentTemplate TargetName="~sitecollection/siteassets/ct1document.docx"/>
    </pnp:ContentType>
```
Files are added upfront using:
```XML
  <pnp:Files>
    <pnp:File Src="CT1Document.docx" Folder="SiteAssets" Overwrite="true" />
  </pnp:Files>
```
Can you retest with the latest engine version and let us know if this still is a problem for you.

**Comment by jansenbe** [comment]
Hmm....maybe I'm wrong...let me do some more testing

**Comment by jansenbe** [comment]
We indeed had an issue in the XML formatter. I've fixed this for the 201512 formatter. Change will be pushed the dev today. Can you retest using our dev branch?

**Comment by LenCardinal** [comment]
Hello, Yes. I will try to get to this today.

**Comment by bturkenburg** [comment]
Hi @LenCardinal did you already test the fix?

**Comment by LenCardinal** [comment]
I have not. I will not be able to for many days….go on without me.

Len Cardinal, Principal Consultant | Microsoft Services, New York / New Jersey | W: (646) 225-4314 | M: (917) 701-0121 | lenc@microsoft.com

**Comment by bturkenburg** [comment]
Hi @jansenbe, I did a test (debug build from dev branch -> reference in Partner Pack) and I think it is not yet solved:

1. I've got the DocumentTemplate element in the xml, but the targetname has the site collection url from the template site: "/sites/template/SiteAssets/TestDocument.docx", missing the ~sitecollection.
2. I'm missing the complete element section Files with the reference to the document and the location.

**Comment by konraplo** [comment]
Hi @bturkenburg 

I will try to test it on the newest branch also;)

Thx for quick feedback!
Konrad

**Comment by konraplo** [comment]
I have tested it and  I can find DocumentTemplate element in the xml but the Files section is missing.
There is another issue according this topic but by apply template with this setting.
So I have exported Template with one Content type witt DocumentTemplate.
I have in my Template something like this:
DocumentTemplate TargetName="templateKpl.dotx"

When I try to provision this template I have got error:
{"urlOfFile\r\nParameter name: Specified value is not supported for the urlOfFile parameter."}

The Problem is that if the Content type is created with this property in this schema ,the SharePoint try to find Document template in folder /_cts/[content type name] und such file doesn't exist.

So I think this property should be set after provisioning File section when this File is already there.

KR
Konrad

**Comment by PaoloPia** [comment]
Hi Konrad,
the reason why you get the issue is that we do not export content, but just the information architecture. So, if you want to have the <pnp:File /> element for the template document, you will have to add it manually to the template (after exporting it), or you can write a custom extension for the engine, which will include the document templates in the export phase. I will close this issue because the observed behavior is "by design". I'm sorry and thanks for your feedback.
