### ISSUE TITLE
Provisioning Engine: Taxonomy Fields not exported correctly

### ISSUE THREAD

**Issue by paulpascha** [SharePoint/PnP-Sites-Core#499]
I've extracted a Provisioning Template XML from an existing site (in this case using PowerShell Get-SPOProvisioningTemplate). I then applied this template to another site. After applying this template I was unable to add List Items (or documents) with Managed Metadata columns that were extracted from my existing site.

For each Managed Metadata column in my Content Type the error I got was: "The SPListItem being updated was not retrieved with all taxonomy fields." (in New Item List Form).

I investigated the extracted Taxonomy Fields and noticed each one contains a "WebId" attribute containing the GUID of the web the fields were extracted from. I removed this attribute from the exported XML and reapplied the template to another site. In this site everything works fine.

BTW: another attribute that should probably be removed from each exported field is sourceid. This also typically contains the GUID of the web the template was extracted from and might cause unexpected results too...

**Comment by PieterVeenstra** [comment]
Hi Paul,

The only thing that needs to be adjusted is the SSPID assuming that your sites live within a different tenant. When I've updated my SSPID my taxonomy fields are importable from any site to any site.

**Comment by paulpascha** [comment]
Hi Pieter,

In this case the sites are created in the same tenant. The taxonomy fields are imported, but creating content using them doesn't work with the exported WebId attribute and its associated value

**Comment by PieterVeenstra** [comment]
are the sites within the same site collection? If they are then are the fields created at the root level of the site collection?

**Comment by paulpascha** [comment]
yes, to both questions...

**Comment by PieterVeenstra** [comment]
I've had the same error many times but this was always down to the same issue where the SSPID wasn't right. 

Could you try and reapply the taxonomy fields to your root site. I've seen that once get sid of the error in the sub sites. My guess is that when the fields are reapplied at the root level something within the taxonomy fields is fixed. 

So simply an export and import of the root site will probably do. Maybe as a sub site template is applied SharePoint internally sees that as a change to the field at the sub site level.

**Comment by paulpascha** [comment]
I'm sorry, my previous comment was not correct. Both sites (source and target) are subsites of different site collections. I have different ProvisioningTemplates for provisioning site-collection level elements and subsite level elements. The site-collection template provisions the fields and content types, the subsite level template provisions ListInstances in which the Fields are referenced

**Comment by PieterVeenstra** [comment]
Ok, I would then reapply a template with these taxonomy fields at each root web of the site collections where the fields are broken in the sub sites. At least that sorted it for me in the past.

**Comment by paulpascha** [comment]
That might be a workaround for now, but then there's still an issue...

Another way to fix the issue in my case was to remove all <Field> elements from the exported <ListInstance>. A <ContentTypeBinding> already causes all fields I need to be added correctly so the additional processing of <Field> elements is not needed.

**Comment by ntinykumar** [comment]
I am facing the same issue and still not working after updating SSPID of deployment tenanat. 

I have used Term store for root site column and that site column I am using in Content Type. When I use this content Type in Page Library then metadata fields are not saving the data. Its still showing the error "The SPListItem being updated was not retrieved with all taxonomy fields."

Some scenario is I have created VS sandbox solution and deploying it to Office 365 as well as on local share point premises. Not working on both cases. 

What is the exact issue? what is the final fix for this ?

**Comment by jansenbe** [comment]
Hi @ntinykumar , our testing showed your scenario to be working. Can you please provide us a clean template so we can verify? Also do know there's lot of sample templates which we use in our nightly unit tests which you can get from here: https://github.com/SharePoint/PnP-Sites-Core/tree/dev/Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates

**Comment by jansenbe** [comment]
Closing this issue since we've not received feedback for a long time. We want to further investigate this, but if there's no feedback we can't. Absolutely fine for you to re-open the issue if you can still re-produce using the March 2017 release or if you have additional context that can help.
